jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
        - "${JACKETT_PORT}:9117"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${JACKETT_DIR}/config/:/config
        - ${JACKETT_DIR}/downloads/:/downloads
    expose:
        - 9117
sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
        - "${SONARR_PORT}:8989"
    links:
        - jackett
    volumes:
        - /dev/rts:/dev/rtc:ro
        - ${SONARR_DIR}/config:/config
        - ${TV_DIR}:/tv
        - ${BTSYNC_DIR}/watch:/downloads
btsync:
    image: bittorrent/sync
    container_name: btsync
    ports:
        - "55555"
        - "${BTSYNC_PORT}:8888"
    volumes:
        - ${BTSYNC_DIR}:/mnt/mounted_folders
        - ${SONARR_DIR}/downloads:/downloads